name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: '4.5.0'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Specify the Node.js version used in your project
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
